[package]
name = "faucet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.20"
rand = "0.8.5"
simple_logger = "4.3.3"
tmi = "0.4.0"
